services:
  trading-bot:
    build: .
    container_name: trading-bot-automated-trading-bot-1
    restart: unless-stopped
    # --- NOUVELLE SECTION AJOUTÉE ICI ---
    volumes:
      # Syntaxe: [dossier sur la machine hôte]:[dossier dans le conteneur]
      - ./logs:/app/logs

networks:
  default:
    name: trading-bot-automated_default
